name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Version Bump & Create Release PR
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Determine registry
        id: registry
        run: |
          if [[ "${{ github.repository_owner }}" == "monorist" ]]; then
            echo "registry=https://registry.npmjs.org/" >> $GITHUB_OUTPUT
            echo "token=${{ secrets.NPM_TOKEN }}" >> $GITHUB_OUTPUT
          else
            echo "registry=https://npm.pkg.github.com/" >> $GITHUB_OUTPUT
            echo "token=${{ secrets.GITHUB_PUBLISH_TOKEN || secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
          fi

      - name: Set .npmrc
        run: |
          echo "registry=${{ steps.registry.outputs.registry }}" > .npmrc
          echo "//$(echo ${{ steps.registry.outputs.registry }} | cut -d/ -f3)/:_authToken=${{ steps.registry.outputs.token }}" >> .npmrc

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
          version: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
